//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Scripts/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""DanceControls"",
            ""id"": ""e38dc9af-913d-4df1-a536-849fdbfe3593"",
            ""actions"": [
                {
                    ""name"": ""MoveL"",
                    ""type"": ""Value"",
                    ""id"": ""e7d64aa6-6835-4c27-bd61-6c4fd737f393"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveR"",
                    ""type"": ""Value"",
                    ""id"": ""49b7d592-f520-4db6-951b-7d17750da3ab"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Boop"",
                    ""type"": ""Button"",
                    ""id"": ""e3034d1f-5f38-40f2-8659-532daec9db47"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchObjectL"",
                    ""type"": ""Button"",
                    ""id"": ""b6d27f35-8cff-4a52-81f2-2108a692175f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchObjectR"",
                    ""type"": ""Button"",
                    ""id"": ""98a588c7-f0b9-43f4-bcd5-f635e0670095"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Record"",
                    ""type"": ""Button"",
                    ""id"": ""e06d41e8-df3e-4e98-a13b-a6576811643c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Play"",
                    ""type"": ""Button"",
                    ""id"": ""b30910d4-5296-430c-84c6-d7ca041d53a1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3f940430-de04-44de-92ec-e2639b9d485d"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9b6e001e-67f3-4d80-b8ea-dbd64fafd566"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Boop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""902b0810-a483-4777-bd9a-8b8e5399c8b8"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Boop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""69295f4a-ade5-4005-b573-b1495402452a"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Boop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2988367c-6335-42f4-a285-0552e5272e00"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Boop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8224df10-41b7-4ea9-82fa-acbd076f5c87"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchObjectL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a19c530-f900-4383-81c3-95e5b3da89d1"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c2703a6-fe47-46d2-84f5-baeec28cbb7a"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchObjectR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8cf1fe23-c3ea-45f1-9f44-9b37765e69d2"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Record"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0118f00b-30ff-42f1-bfd0-f97840cdca86"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Play"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // DanceControls
        m_DanceControls = asset.FindActionMap("DanceControls", throwIfNotFound: true);
        m_DanceControls_MoveL = m_DanceControls.FindAction("MoveL", throwIfNotFound: true);
        m_DanceControls_MoveR = m_DanceControls.FindAction("MoveR", throwIfNotFound: true);
        m_DanceControls_Boop = m_DanceControls.FindAction("Boop", throwIfNotFound: true);
        m_DanceControls_SwitchObjectL = m_DanceControls.FindAction("SwitchObjectL", throwIfNotFound: true);
        m_DanceControls_SwitchObjectR = m_DanceControls.FindAction("SwitchObjectR", throwIfNotFound: true);
        m_DanceControls_Record = m_DanceControls.FindAction("Record", throwIfNotFound: true);
        m_DanceControls_Play = m_DanceControls.FindAction("Play", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // DanceControls
    private readonly InputActionMap m_DanceControls;
    private List<IDanceControlsActions> m_DanceControlsActionsCallbackInterfaces = new List<IDanceControlsActions>();
    private readonly InputAction m_DanceControls_MoveL;
    private readonly InputAction m_DanceControls_MoveR;
    private readonly InputAction m_DanceControls_Boop;
    private readonly InputAction m_DanceControls_SwitchObjectL;
    private readonly InputAction m_DanceControls_SwitchObjectR;
    private readonly InputAction m_DanceControls_Record;
    private readonly InputAction m_DanceControls_Play;
    public struct DanceControlsActions
    {
        private @PlayerControls m_Wrapper;
        public DanceControlsActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveL => m_Wrapper.m_DanceControls_MoveL;
        public InputAction @MoveR => m_Wrapper.m_DanceControls_MoveR;
        public InputAction @Boop => m_Wrapper.m_DanceControls_Boop;
        public InputAction @SwitchObjectL => m_Wrapper.m_DanceControls_SwitchObjectL;
        public InputAction @SwitchObjectR => m_Wrapper.m_DanceControls_SwitchObjectR;
        public InputAction @Record => m_Wrapper.m_DanceControls_Record;
        public InputAction @Play => m_Wrapper.m_DanceControls_Play;
        public InputActionMap Get() { return m_Wrapper.m_DanceControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DanceControlsActions set) { return set.Get(); }
        public void AddCallbacks(IDanceControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_DanceControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DanceControlsActionsCallbackInterfaces.Add(instance);
            @MoveL.started += instance.OnMoveL;
            @MoveL.performed += instance.OnMoveL;
            @MoveL.canceled += instance.OnMoveL;
            @MoveR.started += instance.OnMoveR;
            @MoveR.performed += instance.OnMoveR;
            @MoveR.canceled += instance.OnMoveR;
            @Boop.started += instance.OnBoop;
            @Boop.performed += instance.OnBoop;
            @Boop.canceled += instance.OnBoop;
            @SwitchObjectL.started += instance.OnSwitchObjectL;
            @SwitchObjectL.performed += instance.OnSwitchObjectL;
            @SwitchObjectL.canceled += instance.OnSwitchObjectL;
            @SwitchObjectR.started += instance.OnSwitchObjectR;
            @SwitchObjectR.performed += instance.OnSwitchObjectR;
            @SwitchObjectR.canceled += instance.OnSwitchObjectR;
            @Record.started += instance.OnRecord;
            @Record.performed += instance.OnRecord;
            @Record.canceled += instance.OnRecord;
            @Play.started += instance.OnPlay;
            @Play.performed += instance.OnPlay;
            @Play.canceled += instance.OnPlay;
        }

        private void UnregisterCallbacks(IDanceControlsActions instance)
        {
            @MoveL.started -= instance.OnMoveL;
            @MoveL.performed -= instance.OnMoveL;
            @MoveL.canceled -= instance.OnMoveL;
            @MoveR.started -= instance.OnMoveR;
            @MoveR.performed -= instance.OnMoveR;
            @MoveR.canceled -= instance.OnMoveR;
            @Boop.started -= instance.OnBoop;
            @Boop.performed -= instance.OnBoop;
            @Boop.canceled -= instance.OnBoop;
            @SwitchObjectL.started -= instance.OnSwitchObjectL;
            @SwitchObjectL.performed -= instance.OnSwitchObjectL;
            @SwitchObjectL.canceled -= instance.OnSwitchObjectL;
            @SwitchObjectR.started -= instance.OnSwitchObjectR;
            @SwitchObjectR.performed -= instance.OnSwitchObjectR;
            @SwitchObjectR.canceled -= instance.OnSwitchObjectR;
            @Record.started -= instance.OnRecord;
            @Record.performed -= instance.OnRecord;
            @Record.canceled -= instance.OnRecord;
            @Play.started -= instance.OnPlay;
            @Play.performed -= instance.OnPlay;
            @Play.canceled -= instance.OnPlay;
        }

        public void RemoveCallbacks(IDanceControlsActions instance)
        {
            if (m_Wrapper.m_DanceControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDanceControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_DanceControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DanceControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DanceControlsActions @DanceControls => new DanceControlsActions(this);
    public interface IDanceControlsActions
    {
        void OnMoveL(InputAction.CallbackContext context);
        void OnMoveR(InputAction.CallbackContext context);
        void OnBoop(InputAction.CallbackContext context);
        void OnSwitchObjectL(InputAction.CallbackContext context);
        void OnSwitchObjectR(InputAction.CallbackContext context);
        void OnRecord(InputAction.CallbackContext context);
        void OnPlay(InputAction.CallbackContext context);
    }
}
